// Meal database for PoC - deterministic meal planning
export interface Meal {
  id: string;
  name: string;
  description: string;
  prepTime: string;
  servings: number;
  tags: string[];
  ingredients: string[];
  mealType: "breakfast" | "lunch" | "dinner";
  cuisine: string[];
  proteinSources: string[];
  carbSources: string[];
  fatSources: string[];
  estimatedCalories: number;
  estimatedProtein: number; // grams
  estimatedCarbs: number; // grams
  estimatedFats: number; // grams
  containsAllergens: string[]; // allergens this meal contains
  dietaryRestrictions: string[]; // restrictions this meal fits (e.g., "Vegetarian", "Vegan")
  medicalFriendly: string[]; // medical conditions this meal is suitable for
  medicationSafe: string[]; // medications this meal is safe with
}

// Meal database - expanded set of meals for variety
export const MEAL_DATABASE: Meal[] = [
  // BREAKFAST MEALS
  {
    id: "bf-001",
    name: "Scrambled Eggs with Whole Wheat Toast",
    description: "Fluffy scrambled eggs served with buttered whole wheat toast and a side of fresh berries",
    prepTime: "15 min",
    servings: 1,
    tags: ["High Protein", "Quick", "Classic"],
    ingredients: ["Eggs", "Whole Wheat Bread", "Butter", "Berries", "Salt", "Pepper"],
    mealType: "breakfast",
    cuisine: ["American"],
    proteinSources: ["Eggs"],
    carbSources: ["Bread"],
    fatSources: ["Butter", "Whole Eggs"],
    estimatedCalories: 350,
    estimatedProtein: 20,
    estimatedCarbs: 30,
    estimatedFats: 15,
    containsAllergens: ["Eggs", "Wheat/Gluten", "Milk/Dairy"],
    dietaryRestrictions: ["Vegetarian"],
    medicalFriendly: ["Type 2 Diabetes", "High Cholesterol"],
    medicationSafe: [],
  },
  {
    id: "bf-002",
    name: "Greek Yogurt Parfait",
    description: "Layered Greek yogurt with granola, fresh berries, and a drizzle of honey",
    prepTime: "10 min",
    servings: 1,
    tags: ["High Protein", "Quick", "Healthy"],
    ingredients: ["Greek Yogurt", "Granola", "Berries", "Honey", "Almonds"],
    mealType: "breakfast",
    cuisine: ["Greek", "Mediterranean"],
    proteinSources: ["Greek Yogurt"],
    carbSources: ["Granola", "Fruit"],
    fatSources: ["Nuts"],
    estimatedCalories: 400,
    estimatedProtein: 25,
    estimatedCarbs: 45,
    estimatedFats: 12,
    containsAllergens: ["Milk/Dairy", "Tree Nuts"],
    dietaryRestrictions: ["Vegetarian"],
    medicalFriendly: ["Type 2 Diabetes", "High Cholesterol"],
    medicationSafe: [],
  },
  {
    id: "bf-003",
    name: "Oatmeal with Banana and Peanut Butter",
    description: "Warm oatmeal topped with sliced banana, peanut butter, and a sprinkle of cinnamon",
    prepTime: "10 min",
    servings: 1,
    tags: ["Comfort Food", "High Fiber", "Quick"],
    ingredients: ["Oats", "Banana", "Peanut Butter", "Cinnamon", "Milk"],
    mealType: "breakfast",
    cuisine: ["American"],
    proteinSources: ["Legumes"],
    carbSources: ["Oats", "Fruit"],
    fatSources: ["Nut Butters"],
    estimatedCalories: 450,
    estimatedProtein: 15,
    estimatedCarbs: 60,
    estimatedFats: 18,
    containsAllergens: ["Peanuts", "Milk/Dairy"],
    dietaryRestrictions: ["Vegetarian"],
    medicalFriendly: ["Type 2 Diabetes", "High Cholesterol"],
    medicationSafe: [],
  },
  {
    id: "bf-004",
    name: "Avocado Toast with Poached Eggs",
    description: "Sourdough toast topped with mashed avocado, poached eggs, and a sprinkle of red pepper flakes",
    prepTime: "20 min",
    servings: 1,
    tags: ["High Protein", "Trendy", "Healthy"],
    ingredients: ["Sourdough Bread", "Avocado", "Eggs", "Red Pepper Flakes", "Lemon", "Salt"],
    mealType: "breakfast",
    cuisine: ["American", "Mediterranean"],
    proteinSources: ["Eggs"],
    carbSources: ["Bread"],
    fatSources: ["Avocado", "Whole Eggs"],
    estimatedCalories: 420,
    estimatedProtein: 18,
    estimatedCarbs: 35,
    estimatedFats: 22,
    containsAllergens: ["Eggs", "Wheat/Gluten"],
    dietaryRestrictions: ["Vegetarian"],
    medicalFriendly: ["Type 2 Diabetes"],
    medicationSafe: [],
  },
  {
    id: "bf-005",
    name: "Chicken Sausage and Vegetable Scramble",
    description: "Scrambled eggs with chicken sausage, bell peppers, onions, and spinach",
    prepTime: "20 min",
    servings: 1,
    tags: ["High Protein", "Savory", "Balanced"],
    ingredients: ["Eggs", "Chicken Sausage", "Bell Peppers", "Onions", "Spinach", "Olive Oil"],
    mealType: "breakfast",
    cuisine: ["American"],
    proteinSources: ["Chicken", "Eggs"],
    carbSources: ["Vegetables"],
    fatSources: ["Olive Oil", "Whole Eggs"],
    estimatedCalories: 380,
    estimatedProtein: 28,
    estimatedCarbs: 15,
    estimatedFats: 22,
    containsAllergens: ["Eggs"],
    dietaryRestrictions: [],
    medicalFriendly: ["Type 2 Diabetes", "High Cholesterol"],
    medicationSafe: [],
  },
  {
    id: "bf-006",
    name: "Smoothie Bowl",
    description: "Blended fruit smoothie topped with granola, coconut flakes, and fresh fruit",
    prepTime: "10 min",
    servings: 1,
    tags: ["Quick", "Refreshing", "Healthy"],
    ingredients: ["Banana", "Berries", "Greek Yogurt", "Granola", "Coconut Flakes", "Honey"],
    mealType: "breakfast",
    cuisine: ["American"],
    proteinSources: ["Greek Yogurt"],
    carbSources: ["Fruit", "Granola"],
    fatSources: ["Coconut Oil"],
    estimatedCalories: 350,
    estimatedProtein: 15,
    estimatedCarbs: 55,
    estimatedFats: 10,
    containsAllergens: ["Milk/Dairy"],
    dietaryRestrictions: ["Vegetarian"],
    medicalFriendly: ["Type 2 Diabetes"],
    medicationSafe: [],
  },
  {
    id: "bf-007",
    name: "Tofu Scramble",
    description: "Scrambled tofu with turmeric, black salt, and mixed vegetables",
    prepTime: "15 min",
    servings: 1,
    tags: ["Vegan", "High Protein", "Plant-Based"],
    ingredients: ["Tofu", "Turmeric", "Black Salt", "Bell Peppers", "Onions", "Olive Oil"],
    mealType: "breakfast",
    cuisine: ["American"],
    proteinSources: ["Tofu"],
    carbSources: ["Vegetables"],
    fatSources: ["Olive Oil"],
    estimatedCalories: 280,
    estimatedProtein: 20,
    estimatedCarbs: 12,
    estimatedFats: 18,
    containsAllergens: ["Soy"],
    dietaryRestrictions: ["Vegan", "Vegetarian"],
    medicalFriendly: ["Type 2 Diabetes", "High Cholesterol"],
    medicationSafe: [],
  },
  {
    id: "bf-008",
    name: "Quinoa Breakfast Bowl",
    description: "Warm quinoa cooked in almond milk, topped with nuts, seeds, and fresh fruit",
    prepTime: "20 min",
    servings: 1,
    tags: ["High Protein", "Gluten-Free", "Healthy"],
    ingredients: ["Quinoa", "Almond Milk", "Almonds", "Chia Seeds", "Berries", "Honey"],
    mealType: "breakfast",
    cuisine: ["American"],
    proteinSources: ["Legumes"],
    carbSources: ["Quinoa", "Fruit"],
    fatSources: ["Nuts", "Seeds"],
    estimatedCalories: 400,
    estimatedProtein: 18,
    estimatedCarbs: 50,
    estimatedFats: 15,
    containsAllergens: ["Tree Nuts"],
    dietaryRestrictions: ["Vegetarian", "Vegan"],
    medicalFriendly: ["Celiac Disease", "Type 2 Diabetes"],
    medicationSafe: [],
  },

  // LUNCH MEALS
  {
    id: "ln-001",
    name: "Grilled Chicken Salad",
    description: "Mixed greens with grilled chicken breast, cherry tomatoes, cucumbers, and balsamic vinaigrette",
    prepTime: "25 min",
    servings: 1,
    tags: ["High Protein", "Light", "Healthy"],
    ingredients: ["Chicken Breast", "Mixed Greens", "Cherry Tomatoes", "Cucumbers", "Balsamic Vinegar", "Olive Oil"],
    mealType: "lunch",
    cuisine: ["American", "Mediterranean"],
    proteinSources: ["Chicken"],
    carbSources: ["Vegetables"],
    fatSources: ["Olive Oil"],
    estimatedCalories: 450,
    estimatedProtein: 35,
    estimatedCarbs: 20,
    estimatedFats: 25,
    containsAllergens: [],
    dietaryRestrictions: [],
    medicalFriendly: ["Type 2 Diabetes", "High Cholesterol", "Hypertension"],
    medicationSafe: [],
  },
  {
    id: "ln-002",
    name: "Salmon Teriyaki Bowl",
    description: "Grilled salmon with teriyaki glaze, served over jasmine rice with steamed broccoli",
    prepTime: "30 min",
    servings: 1,
    tags: ["High Protein", "Asian", "Balanced"],
    ingredients: ["Salmon", "Jasmine Rice", "Broccoli", "Teriyaki Sauce", "Sesame Seeds", "Green Onions"],
    mealType: "lunch",
    cuisine: ["Asian", "Japanese"],
    proteinSources: ["Salmon", "Fish"],
    carbSources: ["Rice"],
    fatSources: ["Fatty Fish"],
    estimatedCalories: 550,
    estimatedProtein: 32,
    estimatedCarbs: 55,
    estimatedFats: 18,
    containsAllergens: ["Fish", "Sesame", "Soy"],
    dietaryRestrictions: ["Pescatarian"],
    medicalFriendly: ["Type 2 Diabetes", "High Cholesterol"],
    medicationSafe: [],
  },
  {
    id: "ln-003",
    name: "Mediterranean Quinoa Bowl",
    description: "Quinoa topped with chickpeas, feta cheese, olives, tomatoes, and a lemon-herb dressing",
    prepTime: "25 min",
    servings: 1,
    tags: ["Vegetarian", "High Protein", "Mediterranean"],
    ingredients: ["Quinoa", "Chickpeas", "Feta Cheese", "Olives", "Tomatoes", "Lemon", "Olive Oil"],
    mealType: "lunch",
    cuisine: ["Mediterranean", "Greek"],
    proteinSources: ["Legumes", "Greek Yogurt"],
    carbSources: ["Quinoa", "Beans"],
    fatSources: ["Olive Oil", "Cheese"],
    estimatedCalories: 520,
    estimatedProtein: 22,
    estimatedCarbs: 60,
    estimatedFats: 20,
    containsAllergens: ["Milk/Dairy"],
    dietaryRestrictions: ["Vegetarian"],
    medicalFriendly: ["Type 2 Diabetes", "High Cholesterol"],
    medicationSafe: [],
  },
  {
    id: "ln-004",
    name: "Turkey and Avocado Wrap",
    description: "Whole wheat tortilla filled with sliced turkey, avocado, lettuce, and tomato",
    prepTime: "10 min",
    servings: 1,
    tags: ["Quick", "High Protein", "Portable"],
    ingredients: ["Whole Wheat Tortilla", "Turkey", "Avocado", "Lettuce", "Tomato", "Mayonnaise"],
    mealType: "lunch",
    cuisine: ["American"],
    proteinSources: ["Turkey"],
    carbSources: ["Bread"],
    fatSources: ["Avocado"],
    estimatedCalories: 480,
    estimatedProtein: 28,
    estimatedCarbs: 40,
    estimatedFats: 22,
    containsAllergens: ["Wheat/Gluten", "Eggs"],
    dietaryRestrictions: [],
    medicalFriendly: ["Type 2 Diabetes"],
    medicationSafe: [],
  },
  {
    id: "ln-005",
    name: "Beef Stir-Fry with Vegetables",
    description: "Sliced beef stir-fried with bell peppers, broccoli, and carrots in a savory sauce, served over rice",
    prepTime: "25 min",
    servings: 1,
    tags: ["High Protein", "Asian", "Comfort Food"],
    ingredients: ["Beef", "Bell Peppers", "Broccoli", "Carrots", "Rice", "Soy Sauce", "Ginger", "Garlic"],
    mealType: "lunch",
    cuisine: ["Asian", "Chinese"],
    proteinSources: ["Beef"],
    carbSources: ["Rice"],
    fatSources: ["Olive Oil"],
    estimatedCalories: 580,
    estimatedProtein: 38,
    estimatedCarbs: 55,
    estimatedFats: 20,
    containsAllergens: ["Soy", "Wheat/Gluten"],
    dietaryRestrictions: [],
    medicalFriendly: ["Type 2 Diabetes"],
    medicationSafe: [],
  },
  {
    id: "ln-006",
    name: "Lentil Soup with Whole Grain Bread",
    description: "Hearty lentil soup with vegetables, served with a slice of whole grain bread",
    prepTime: "35 min",
    servings: 1,
    tags: ["Vegetarian", "Comfort Food", "High Fiber"],
    ingredients: ["Lentils", "Carrots", "Celery", "Onions", "Tomatoes", "Whole Grain Bread", "Olive Oil"],
    mealType: "lunch",
    cuisine: ["Mediterranean", "Middle Eastern"],
    proteinSources: ["Legumes"],
    carbSources: ["Lentils", "Bread"],
    fatSources: ["Olive Oil"],
    estimatedCalories: 420,
    estimatedProtein: 20,
    estimatedCarbs: 65,
    estimatedFats: 10,
    containsAllergens: ["Wheat/Gluten", "Celery"],
    dietaryRestrictions: ["Vegetarian", "Vegan"],
    medicalFriendly: ["Type 2 Diabetes", "High Cholesterol"],
    medicationSafe: [],
  },
  {
    id: "ln-007",
    name: "Tuna Salad Sandwich",
    description: "Classic tuna salad with mayonnaise and celery, served on whole wheat bread",
    prepTime: "15 min",
    servings: 1,
    tags: ["Quick", "High Protein", "Classic"],
    ingredients: ["Tuna", "Mayonnaise", "Celery", "Whole Wheat Bread", "Lettuce", "Onions"],
    mealType: "lunch",
    cuisine: ["American"],
    proteinSources: ["Tuna", "Fish"],
    carbSources: ["Bread"],
    fatSources: ["Mayonnaise"],
    estimatedCalories: 450,
    estimatedProtein: 30,
    estimatedCarbs: 35,
    estimatedFats: 20,
    containsAllergens: ["Fish", "Eggs", "Wheat/Gluten", "Celery"],
    dietaryRestrictions: ["Pescatarian"],
    medicalFriendly: ["Type 2 Diabetes"],
    medicationSafe: [],
  },
  {
    id: "ln-008",
    name: "Chicken Caesar Salad",
    description: "Romaine lettuce with grilled chicken, parmesan cheese, croutons, and Caesar dressing",
    prepTime: "20 min",
    servings: 1,
    tags: ["High Protein", "Classic", "Satisfying"],
    ingredients: ["Chicken Breast", "Romaine Lettuce", "Parmesan Cheese", "Croutons", "Caesar Dressing", "Lemon"],
    mealType: "lunch",
    cuisine: ["American", "Italian"],
    proteinSources: ["Chicken"],
    carbSources: ["Bread"],
    fatSources: ["Cheese"],
    estimatedCalories: 520,
    estimatedProtein: 38,
    estimatedCarbs: 25,
    estimatedFats: 28,
    containsAllergens: ["Milk/Dairy", "Wheat/Gluten", "Eggs"],
    dietaryRestrictions: [],
    medicalFriendly: ["Type 2 Diabetes"],
    medicationSafe: [],
  },
  {
    id: "ln-009",
    name: "Veggie Burger with Sweet Potato Fries",
    description: "Plant-based burger patty on a whole grain bun with lettuce, tomato, and baked sweet potato fries",
    prepTime: "30 min",
    servings: 1,
    tags: ["Vegetarian", "Comfort Food", "Satisfying"],
    ingredients: ["Veggie Burger Patty", "Whole Grain Bun", "Lettuce", "Tomato", "Sweet Potatoes", "Olive Oil"],
    mealType: "lunch",
    cuisine: ["American"],
    proteinSources: ["Legumes"],
    carbSources: ["Bread", "Sweet Potatoes"],
    fatSources: ["Olive Oil"],
    estimatedCalories: 550,
    estimatedProtein: 18,
    estimatedCarbs: 70,
    estimatedFats: 18,
    containsAllergens: ["Wheat/Gluten", "Soy"],
    dietaryRestrictions: ["Vegetarian", "Vegan"],
    medicalFriendly: ["Type 2 Diabetes"],
    medicationSafe: [],
  },
  {
    id: "ln-010",
    name: "Shrimp Pad Thai",
    description: "Stir-fried rice noodles with shrimp, eggs, bean sprouts, and peanuts in a tangy sauce",
    prepTime: "25 min",
    servings: 1,
    tags: ["High Protein", "Asian", "Flavorful"],
    ingredients: ["Shrimp", "Rice Noodles", "Eggs", "Bean Sprouts", "Peanuts", "Lime", "Fish Sauce"],
    mealType: "lunch",
    cuisine: ["Thai", "Asian"],
    proteinSources: ["Shrimp", "Eggs"],
    carbSources: ["Pasta"],
    fatSources: ["Peanuts"],
    estimatedCalories: 520,
    estimatedProtein: 28,
    estimatedCarbs: 60,
    estimatedFats: 15,
    containsAllergens: ["Shellfish", "Eggs", "Peanuts", "Fish"],
    dietaryRestrictions: ["Pescatarian"],
    medicalFriendly: ["Type 2 Diabetes"],
    medicationSafe: [],
  },

  // DINNER MEALS
  {
    id: "dn-001",
    name: "Grilled Salmon with Roasted Vegetables",
    description: "Herb-crusted salmon fillet with roasted broccoli, carrots, and quinoa",
    prepTime: "35 min",
    servings: 1,
    tags: ["High Protein", "Healthy", "Balanced"],
    ingredients: ["Salmon", "Broccoli", "Carrots", "Quinoa", "Lemon", "Olive Oil", "Herbs"],
    mealType: "dinner",
    cuisine: ["Mediterranean", "American"],
    proteinSources: ["Salmon", "Fish"],
    carbSources: ["Quinoa"],
    fatSources: ["Fatty Fish", "Olive Oil"],
    estimatedCalories: 580,
    estimatedProtein: 40,
    estimatedCarbs: 45,
    estimatedFats: 25,
    containsAllergens: ["Fish"],
    dietaryRestrictions: ["Pescatarian"],
    medicalFriendly: ["Type 2 Diabetes", "High Cholesterol", "Heart Disease"],
    medicationSafe: [],
  },
  {
    id: "dn-002",
    name: "Chicken Tikka Masala",
    description: "Tender chicken in a creamy tomato-based curry sauce, served with basmati rice and naan",
    prepTime: "40 min",
    servings: 1,
    tags: ["High Protein", "Indian", "Comfort Food"],
    ingredients: ["Chicken", "Tomatoes", "Cream", "Basmati Rice", "Naan", "Spices", "Onions"],
    mealType: "dinner",
    cuisine: ["Indian"],
    proteinSources: ["Chicken"],
    carbSources: ["Rice", "Bread"],
    fatSources: ["Butter", "Coconut Oil"],
    estimatedCalories: 650,
    estimatedProtein: 42,
    estimatedCarbs: 65,
    estimatedFats: 22,
    containsAllergens: ["Milk/Dairy", "Wheat/Gluten"],
    dietaryRestrictions: [],
    medicalFriendly: ["Type 2 Diabetes"],
    medicationSafe: [],
  },
  {
    id: "dn-003",
    name: "Spaghetti with Meatballs",
    description: "Classic spaghetti pasta with homemade meatballs in marinara sauce, topped with parmesan",
    prepTime: "45 min",
    servings: 1,
    tags: ["Comfort Food", "High Protein", "Italian"],
    ingredients: ["Spaghetti", "Ground Beef", "Tomatoes", "Parmesan Cheese", "Garlic", "Basil", "Olive Oil"],
    mealType: "dinner",
    cuisine: ["Italian"],
    proteinSources: ["Beef"],
    carbSources: ["Pasta"],
    fatSources: ["Olive Oil", "Cheese"],
    estimatedCalories: 680,
    estimatedProtein: 38,
    estimatedCarbs: 75,
    estimatedFats: 22,
    containsAllergens: ["Wheat/Gluten", "Milk/Dairy", "Eggs"],
    dietaryRestrictions: [],
    medicalFriendly: ["Type 2 Diabetes"],
    medicationSafe: [],
  },
  {
    id: "dn-004",
    name: "Beef Tacos",
    description: "Seasoned ground beef in corn tortillas with lettuce, tomatoes, cheese, and salsa",
    prepTime: "25 min",
    servings: 1,
    tags: ["High Protein", "Mexican", "Quick"],
    ingredients: ["Ground Beef", "Corn Tortillas", "Lettuce", "Tomatoes", "Cheese", "Salsa", "Sour Cream"],
    mealType: "dinner",
    cuisine: ["Mexican"],
    proteinSources: ["Beef"],
    carbSources: ["Corn"],
    fatSources: ["Cheese"],
    estimatedCalories: 620,
    estimatedProtein: 35,
    estimatedCarbs: 50,
    estimatedFats: 28,
    containsAllergens: ["Milk/Dairy"],
    dietaryRestrictions: [],
    medicalFriendly: ["Type 2 Diabetes"],
    medicationSafe: [],
  },
  {
    id: "dn-005",
    name: "Vegetarian Buddha Bowl",
    description: "Bowl with brown rice, roasted sweet potatoes, black beans, avocado, and tahini dressing",
    prepTime: "35 min",
    servings: 1,
    tags: ["Vegetarian", "High Fiber", "Healthy"],
    ingredients: ["Brown Rice", "Sweet Potatoes", "Black Beans", "Avocado", "Tahini", "Lemon", "Kale"],
    mealType: "dinner",
    cuisine: ["American", "Mediterranean"],
    proteinSources: ["Legumes"],
    carbSources: ["Rice", "Sweet Potatoes", "Beans"],
    fatSources: ["Avocado", "Seeds"],
    estimatedCalories: 580,
    estimatedProtein: 20,
    estimatedCarbs: 75,
    estimatedFats: 22,
    containsAllergens: ["Sesame"],
    dietaryRestrictions: ["Vegetarian", "Vegan"],
    medicalFriendly: ["Type 2 Diabetes", "High Cholesterol"],
    medicationSafe: [],
  },
  {
    id: "dn-006",
    name: "Pork Tenderloin with Mashed Potatoes",
    description: "Herb-roasted pork tenderloin served with creamy mashed potatoes and green beans",
    prepTime: "50 min",
    servings: 1,
    tags: ["High Protein", "Comfort Food", "Classic"],
    ingredients: ["Pork Tenderloin", "Potatoes", "Butter", "Green Beans", "Garlic", "Herbs"],
    mealType: "dinner",
    cuisine: ["American"],
    proteinSources: ["Pork"],
    carbSources: ["Potatoes"],
    fatSources: ["Butter"],
    estimatedCalories: 620,
    estimatedProtein: 45,
    estimatedCarbs: 55,
    estimatedFats: 22,
    containsAllergens: ["Milk/Dairy"],
    dietaryRestrictions: [],
    medicalFriendly: ["Type 2 Diabetes"],
    medicationSafe: [],
  },
  {
    id: "dn-007",
    name: "Lamb Curry with Rice",
    description: "Tender lamb pieces in a rich curry sauce with aromatic spices, served with basmati rice",
    prepTime: "60 min",
    servings: 1,
    tags: ["High Protein", "Indian", "Flavorful"],
    ingredients: ["Lamb", "Tomatoes", "Onions", "Basmati Rice", "Curry Spices", "Coconut Milk", "Ginger"],
    mealType: "dinner",
    cuisine: ["Indian", "Middle Eastern"],
    proteinSources: ["Lamb"],
    carbSources: ["Rice"],
    fatSources: ["Coconut Oil"],
    estimatedCalories: 680,
    estimatedProtein: 48,
    estimatedCarbs: 60,
    estimatedFats: 28,
    containsAllergens: [],
    dietaryRestrictions: ["Halal"],
    medicalFriendly: ["Type 2 Diabetes"],
    medicationSafe: [],
  },
  {
    id: "dn-008",
    name: "Tempeh Stir-Fry",
    description: "Marinated tempeh stir-fried with mixed vegetables in a savory sauce, served over brown rice",
    prepTime: "30 min",
    servings: 1,
    tags: ["Vegan", "High Protein", "Asian"],
    ingredients: ["Tempeh", "Broccoli", "Bell Peppers", "Carrots", "Brown Rice", "Soy Sauce", "Ginger"],
    mealType: "dinner",
    cuisine: ["Asian"],
    proteinSources: ["Tempeh"],
    carbSources: ["Rice"],
    fatSources: ["Olive Oil"],
    estimatedCalories: 520,
    estimatedProtein: 28,
    estimatedCarbs: 65,
    estimatedFats: 15,
    containsAllergens: ["Soy", "Wheat/Gluten"],
    dietaryRestrictions: ["Vegan", "Vegetarian"],
    medicalFriendly: ["Type 2 Diabetes", "High Cholesterol"],
    medicationSafe: [],
  },
  {
    id: "dn-009",
    name: "Turkey Meatballs with Zucchini Noodles",
    description: "Lean turkey meatballs in marinara sauce served over spiralized zucchini noodles",
    prepTime: "35 min",
    servings: 1,
    tags: ["High Protein", "Low-Carb", "Healthy"],
    ingredients: ["Ground Turkey", "Zucchini", "Tomatoes", "Parmesan Cheese", "Garlic", "Basil", "Olive Oil"],
    mealType: "dinner",
    cuisine: ["Italian", "American"],
    proteinSources: ["Turkey"],
    carbSources: ["Vegetables"],
    fatSources: ["Olive Oil", "Cheese"],
    estimatedCalories: 480,
    estimatedProtein: 42,
    estimatedCarbs: 20,
    estimatedFats: 25,
    containsAllergens: ["Milk/Dairy", "Eggs"],
    dietaryRestrictions: [],
    medicalFriendly: ["Type 2 Diabetes", "High Cholesterol", "Hypertension"],
    medicationSafe: [],
  },
  {
    id: "dn-010",
    name: "Baked Cod with Couscous",
    description: "Herb-crusted cod fillet baked to perfection, served with lemon couscous and roasted asparagus",
    prepTime: "30 min",
    servings: 1,
    tags: ["High Protein", "Light", "Mediterranean"],
    ingredients: ["Cod", "Couscous", "Asparagus", "Lemon", "Herbs", "Olive Oil"],
    mealType: "dinner",
    cuisine: ["Mediterranean"],
    proteinSources: ["Fish"],
    carbSources: ["Couscous"],
    fatSources: ["Olive Oil"],
    estimatedCalories: 480,
    estimatedProtein: 38,
    estimatedCarbs: 50,
    estimatedFats: 12,
    containsAllergens: ["Fish", "Wheat/Gluten"],
    dietaryRestrictions: ["Pescatarian"],
    medicalFriendly: ["Type 2 Diabetes", "High Cholesterol", "Heart Disease"],
    medicationSafe: [],
  },
  {
    id: "dn-011",
    name: "Chicken Fajitas",
    description: "Sizzling chicken strips with bell peppers and onions, served with warm tortillas and toppings",
    prepTime: "30 min",
    servings: 1,
    tags: ["High Protein", "Mexican", "Quick"],
    ingredients: ["Chicken", "Bell Peppers", "Onions", "Tortillas", "Sour Cream", "Salsa", "Lime"],
    mealType: "dinner",
    cuisine: ["Mexican"],
    proteinSources: ["Chicken"],
    carbSources: ["Corn"],
    fatSources: ["Sour Cream"],
    estimatedCalories: 580,
    estimatedProtein: 40,
    estimatedCarbs: 55,
    estimatedFats: 20,
    containsAllergens: ["Milk/Dairy"],
    dietaryRestrictions: [],
    medicalFriendly: ["Type 2 Diabetes"],
    medicationSafe: [],
  },
  {
    id: "dn-012",
    name: "Mushroom Risotto",
    description: "Creamy arborio rice cooked with mixed mushrooms, white wine, and parmesan cheese",
    prepTime: "40 min",
    servings: 1,
    tags: ["Vegetarian", "Comfort Food", "Italian"],
    ingredients: ["Arborio Rice", "Mushrooms", "Parmesan Cheese", "White Wine", "Onions", "Butter", "Herbs"],
    mealType: "dinner",
    cuisine: ["Italian"],
    proteinSources: ["Greek Yogurt"],
    carbSources: ["Rice"],
    fatSources: ["Butter", "Cheese"],
    estimatedCalories: 520,
    estimatedProtein: 15,
    estimatedCarbs: 70,
    estimatedFats: 18,
    containsAllergens: ["Milk/Dairy"],
    dietaryRestrictions: ["Vegetarian"],
    medicalFriendly: ["Type 2 Diabetes"],
    medicationSafe: [],
  },
];

// Helper function to get meals by type
export function getMealsByType(mealType: "breakfast" | "lunch" | "dinner"): Meal[] {
  return MEAL_DATABASE.filter((meal) => meal.mealType === mealType);
}

// Helper function to generate a unique meal ID
export function generateMealId(prefix: string): string {
  return `${prefix}-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
}

// Coerce LLM-generated JSON object into a valid Meal (same style as MEAL_DATABASE).
export function coerceToMeal(obj: unknown, fallbackIdPrefix: string = "llm"): Meal {
  const o = obj as Record<string, unknown>;
  const arr = (v: unknown): string[] => (Array.isArray(v) ? (v as string[]) : []);
  const num = (v: unknown, d: number): number => (typeof v === "number" && !Number.isNaN(v) ? v : d);
  const str = (v: unknown, d: string): string => (typeof v === "string" ? v : d);
  const mealType = (v: unknown): Meal["mealType"] => {
    if (v === "breakfast" || v === "lunch" || v === "dinner") return v;
    return "dinner";
  };
  const id = str(o.id, "").trim() || generateMealId(fallbackIdPrefix);
  return {
    id,
    name: str(o.name, "Unnamed meal"),
    description: str(o.description, ""),
    prepTime: str(o.prepTime, "—"),
    servings: Math.max(1, Math.floor(num(o.servings, 1))),
    tags: arr(o.tags),
    ingredients: arr(o.ingredients),
    mealType: mealType(o.mealType),
    cuisine: arr(o.cuisine),
    proteinSources: arr(o.proteinSources),
    carbSources: arr(o.carbSources),
    fatSources: arr(o.fatSources),
    estimatedCalories: Math.max(0, num(o.estimatedCalories, 0)),
    estimatedProtein: Math.max(0, num(o.estimatedProtein, 0)),
    estimatedCarbs: Math.max(0, num(o.estimatedCarbs, 0)),
    estimatedFats: Math.max(0, num(o.estimatedFats, 0)),
    containsAllergens: arr(o.containsAllergens),
    dietaryRestrictions: arr(o.dietaryRestrictions),
    medicalFriendly: arr(o.medicalFriendly),
    medicationSafe: arr(o.medicationSafe),
  };
}
